[package]
name = "camera-mic-notifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.17.4"
glib = "0.17.8"
gtk = "0.17.1"
